# Generated by Django 3.1.3 on 2020-11-19 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_newsletterrecipients'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='article',
        #     name='article_image',
        #     field=models.ImageField(blank=True, upload_to='articles/'),
        # ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
